name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUDDERSTACK_DATAPLANE_URL:  ${{ secrets.RUDDERSTACK_DATAPLANE_URL }}
      RUDDERSTACK_WRITE_KEY:  ${{ secrets.RUDDERSTACK_WRITE_KEY }}
      
    steps:
      - uses: mwflaher/gh-rudderstack-action@v0.7.0
        with:
          event: BuildStarted
          userId: mwflaher
          properties: >
            {"testProperty":"test_value"}
