name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mwflaher/gh-rudderstack-action@v0.1.0
        with:
          name: BuildStarted
          user: Matt
